[phases.install]
cmds = ["npm install --ignore-scripts"]

[phases.build]
cmds = [
  "npm run build --workspace=gathering-server",
  "cd server && ./node_modules/.bin/prisma generate"
]

[start]
cmd = "cd server && ./node_modules/.bin/prisma db push --accept-data-loss && node dist/index.js"
